### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by thorst** [mkdynamic/jquery-popupwindow#16]
If your interested, I'd be interested in taking over maintaining this. I have a new version I'm about to release which better handles various browser rendering methods (dynamically adjusts height to fit content) and surrounding chrome.

Just let me know and I'll back up my repo and delete it and let you transfer this over.

**Comment by lencioni** [comment]
Sounds good to me. @mkdynamic what do you think?

**Comment by mkdynamic** [comment]
Sounds good. Thanks for the help @thorst.

**Comment by thorst** [comment]
Done

**Comment by brendon** [comment]
@thorst, just wondering if you're still the maintainer of this? I know it's an old script but I'd like to get it into npm so that it can be installed and/or delivered by a CDN :)

**Comment by thorst** [comment]
That's a good question. If I were you, I would clone and then move forward with your version.

**Comment by brendon** [comment]
Hehe :) That's all good. I should probably just rewrite it as a javascript module :) For now though, `jsdelivr` allows one to use it like so:

```
<script src="https://cdn.jsdelivr.net/gh/mkdynamic/jquery-popupwindow@master/jquery.popupwindow.min.js"></script>
```
